-- [EN] Keep all server-side timestamps in UTC for cross-system consistency.
-- [ZH] 伺服器端時間統一使用 UTC，確保跨系統一致性。
SET TIME ZONE 'UTC';

-- [EN] Core organization tables: hospitals / employee / floors / rooms.
-- [ZH] 核心組織資料表：醫院 / 員工 / 樓層 / 房間。
CREATE TABLE IF NOT EXISTS hospitals (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(100) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS employee (
  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_code VARCHAR(50) UNIQUE NOT NULL,
  employee_name VARCHAR(50) NOT NULL,
  role VARCHAR(50),
  is_active BOOLEAN DEFAULT TRUE
);

CREATE TABLE IF NOT EXISTS floors (
  floors_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  hospital_id INTEGER NOT NULL,
  floor_number INTEGER NOT NULL,
  CONSTRAINT unique_hospital_floor UNIQUE (hospital_id, floor_number)
);

CREATE TABLE IF NOT EXISTS rooms (
  room_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  floors_id INTEGER NOT NULL,
  room_number VARCHAR(4) NOT NULL,
  bed_number INTEGER NOT NULL,
  CONSTRAINT uq_rooms_floor_room UNIQUE (floors_id, room_number),
  CONSTRAINT fk_rooms_floors
    FOREIGN KEY (floors_id) REFERENCES floors (floors_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_rooms_floors_id ON rooms (floors_id);

-- [EN] Fixed mock sensor registry used by load-generator.
-- [ZH] 供壓測模擬器使用的固定 mock 感測器清單。
CREATE TABLE IF NOT EXISTS mock_sensors (
  mock_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sensor_ip VARCHAR(45) NOT NULL UNIQUE,
  sensor_number VARCHAR(32) NOT NULL UNIQUE,
  device_type VARCHAR(16) NOT NULL CHECK (device_type IN ('esp32', 'stm32')),
  room_id INTEGER NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT timezone('UTC', now()),
  CONSTRAINT fk_mock_sensors_room
    FOREIGN KEY (room_id) REFERENCES rooms (room_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_mock_sensors_device_type ON mock_sensors (device_type);
CREATE INDEX IF NOT EXISTS idx_mock_sensors_room_id ON mock_sensors (room_id);

-- [EN] Sensor master table.
-- [ZH] 感測器主檔。
CREATE TABLE IF NOT EXISTS sensors (
  sensor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sensor_number VARCHAR(32) NOT NULL UNIQUE,
  device_type VARCHAR(16) NOT NULL,
  floor_id INTEGER,
  room_id INTEGER,
  bed_edge_json JSONB,
  CONSTRAINT fk_sensors_floor
    FOREIGN KEY (floor_id) REFERENCES floors (floors_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT fk_sensors_room
    FOREIGN KEY (room_id) REFERENCES rooms (room_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_sensors_device_type ON sensors (device_type);
CREATE INDEX IF NOT EXISTS idx_sensors_floor_id ON sensors (floor_id);
CREATE INDEX IF NOT EXISTS idx_sensors_room_id ON sensors (room_id);

-- [EN] Unified telemetry table for all platforms.
-- [ZH] 所有平台共用的遙測資料表。
CREATE TABLE IF NOT EXISTS sensor_datas (
  data_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  device_type VARCHAR(16) NOT NULL,
  sensor_id INTEGER,
  breath_rate INTEGER NOT NULL,
  breath_rate_state INTEGER DEFAULT 0,
  heart_rate INTEGER NOT NULL,
  rhythm VARCHAR(32),
  out_of_range INTEGER DEFAULT 0,
  angles_first INTEGER,
  angles_second INTEGER,
  movement_state INTEGER,
  movement_level INTEGER,
  breath_rate_last_transmit BIGINT,
  heart_rate_last_transmit BIGINT,
  distance REAL,
  thermistor REAL,
  temperature_json JSONB NOT NULL,
  high_temperature REAL NOT NULL,
  "timestamp" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT timezone('UTC', now()),
  CONSTRAINT sensor_datas_pk PRIMARY KEY (data_id, "timestamp"),
  CONSTRAINT fk_sensor_datas_sensor
    FOREIGN KEY (sensor_id) REFERENCES sensors (sensor_id)
) PARTITION BY RANGE ("timestamp");

CREATE INDEX IF NOT EXISTS idx_sensor_datas_sensor_id ON sensor_datas (sensor_id);
CREATE INDEX IF NOT EXISTS idx_sensor_datas_device_type_ts ON sensor_datas (device_type, "timestamp");

-- [EN] Default partition catches unexpected timestamps as a safety net.
-- [ZH] 預設分區作為保底，避免異常時間戳導致寫入失敗。
CREATE TABLE IF NOT EXISTS sensor_datas_default PARTITION OF sensor_datas DEFAULT;

-- [EN] Ensure monthly partitions for sensor_datas around current month.
-- [ZH] 自動確保 sensor_datas 在當前月份前後的月分區存在。
CREATE OR REPLACE FUNCTION ensure_sensor_data_monthly_partitions(months_back INTEGER DEFAULT 1, months_ahead INTEGER DEFAULT 3)
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
  base_month DATE := date_trunc('month', timezone('UTC', now()))::date;
  offset_idx INTEGER;
  from_date DATE;
  to_date DATE;
  part_name TEXT;
  created_count INTEGER := 0;
BEGIN
  IF months_back < 0 THEN
    months_back := 0;
  END IF;
  IF months_ahead < 0 THEN
    months_ahead := 0;
  END IF;

  FOR offset_idx IN (-months_back)..months_ahead LOOP
    from_date := (base_month + (offset_idx || ' month')::interval)::date;
    to_date := (from_date + interval '1 month')::date;
    part_name := format('sensor_datas_p%s', to_char(from_date, 'YYYYMM'));

    IF to_regclass('public.' || part_name) IS NULL THEN
      EXECUTE format(
        'CREATE TABLE %I PARTITION OF sensor_datas FOR VALUES FROM (%L) TO (%L)',
        part_name, from_date, to_date
      );
      created_count := created_count + 1;
    END IF;
  END LOOP;

  RETURN created_count;
END;
$$;

SELECT ensure_sensor_data_monthly_partitions(1, 3);

-- [EN] Unified raw log table with device_type and sensor number trace fields.
-- [ZH] 統一原始日誌表，包含 device_type 與 sensor_number 追蹤欄位。
CREATE TABLE IF NOT EXISTS sensor_raw_logs (
  raw_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  device_type VARCHAR(16) NOT NULL,
  sensor_number VARCHAR(50),
  client_ip VARCHAR(45),
  raw_content TEXT,
  processed_content TEXT,
  processed_status SMALLINT NOT NULL DEFAULT 0,
  sensor_data_id BIGINT,
  sensor_data_timestamp TIMESTAMP WITHOUT TIME ZONE,
  "timestamp" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT timezone('UTC', now()),
  CONSTRAINT sensor_raw_logs_pk PRIMARY KEY (raw_id, "timestamp")
) PARTITION BY RANGE ("timestamp");

CREATE INDEX IF NOT EXISTS idx_sensor_raw_logs_device_type_ts ON sensor_raw_logs (device_type, "timestamp");
CREATE INDEX IF NOT EXISTS idx_sensor_raw_logs_sensor_number ON sensor_raw_logs (sensor_number);

-- [EN] Default partition catches unexpected timestamps as a safety net.
-- [ZH] 預設分區作為保底，避免異常時間戳導致寫入失敗。
CREATE TABLE IF NOT EXISTS sensor_raw_logs_default PARTITION OF sensor_raw_logs DEFAULT;

-- [EN] Ensure daily partitions for sensor_raw_logs around current day.
-- [ZH] 自動確保 sensor_raw_logs 在當日前後的日分區存在。
CREATE OR REPLACE FUNCTION ensure_sensor_raw_log_partitions(days_back INTEGER DEFAULT 1, days_ahead INTEGER DEFAULT 7)
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
  base_day DATE := timezone('UTC', now())::date;
  offset_idx INTEGER;
  from_date DATE;
  to_date DATE;
  part_name TEXT;
  created_count INTEGER := 0;
BEGIN
  IF days_back < 0 THEN
    days_back := 0;
  END IF;
  IF days_ahead < 0 THEN
    days_ahead := 0;
  END IF;

  FOR offset_idx IN (-days_back)..days_ahead LOOP
    from_date := base_day + offset_idx;
    to_date := from_date + 1;
    part_name := format('sensor_raw_logs_p%s', to_char(from_date, 'YYYYMMDD'));

    IF to_regclass('public.' || part_name) IS NULL THEN
      EXECUTE format(
        'CREATE TABLE %I PARTITION OF sensor_raw_logs FOR VALUES FROM (%L) TO (%L)',
        part_name, from_date, to_date
      );
      created_count := created_count + 1;
    END IF;
  END LOOP;

  RETURN created_count;
END;
$$;

-- [EN] Drop raw-log daily partitions older than retention days.
-- [ZH] 刪除超過保留天數的 raw-log 日分區。
CREATE OR REPLACE FUNCTION prune_sensor_raw_log_partitions(retention_days INTEGER DEFAULT 30)
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
  cutoff_date DATE := timezone('UTC', now())::date - retention_days;
  rel RECORD;
  part_suffix TEXT;
  part_day DATE;
  dropped_count INTEGER := 0;
BEGIN
  IF retention_days < 1 THEN
    retention_days := 1;
    cutoff_date := timezone('UTC', now())::date - retention_days;
  END IF;

  FOR rel IN
    SELECT c.relname AS partition_name
    FROM pg_class c
    JOIN pg_inherits i ON i.inhrelid = c.oid
    JOIN pg_class p ON p.oid = i.inhparent
    WHERE p.relname = 'sensor_raw_logs'
      AND c.relname LIKE 'sensor_raw_logs_p________'
  LOOP
    part_suffix := substring(rel.partition_name FROM 'sensor_raw_logs_p([0-9]{8})');
    IF part_suffix IS NULL THEN
      CONTINUE;
    END IF;

    part_day := to_date(part_suffix, 'YYYYMMDD');
    IF part_day < cutoff_date THEN
      EXECUTE format('DROP TABLE IF EXISTS %I', rel.partition_name);
      dropped_count := dropped_count + 1;
    END IF;
  END LOOP;

  RETURN dropped_count;
END;
$$;

SELECT ensure_sensor_raw_log_partitions(1, 7);
SELECT prune_sensor_raw_log_partitions(30);

-- [EN] Alert/abnormal event table.
-- [ZH] 異常事件資料表。
CREATE TABLE IF NOT EXISTS is_abnormal (
  abnormal_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sensor_id INTEGER NOT NULL,
  abnormal_type VARCHAR(20) NOT NULL,
  abnormal_value REAL NOT NULL,
  "timestamp" TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  is_confirmed BOOLEAN DEFAULT FALSE,
  CONSTRAINT fk_is_abnormal_sensor
    FOREIGN KEY (sensor_id) REFERENCES sensors (sensor_id)
    ON DELETE CASCADE
    ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_is_abnormal_sensor_id ON is_abnormal (sensor_id);

-- [EN] Patient profile and threshold settings.
-- [ZH] 病患主檔與閾值設定。
CREATE TABLE IF NOT EXISTS patient (
  patient_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_name VARCHAR(100) NOT NULL,
  gender TEXT NOT NULL CHECK (gender IN ('M', 'F')),
  admission_date TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  discharge_date TIMESTAMP WITHOUT TIME ZONE,
  room_id INTEGER,
  notes VARCHAR(100),
  max_breath_rate INTEGER DEFAULT 20,
  min_breath_rate INTEGER DEFAULT 12,
  max_temperature NUMERIC(3, 1) DEFAULT 37.5,
  min_temperature NUMERIC(3, 1) DEFAULT 36.0,
  max_heart_rate INTEGER DEFAULT 100,
  min_heart_rate INTEGER DEFAULT 60,
  calibration VARCHAR(255),
  created_at TIMESTAMP WITHOUT TIME ZONE DEFAULT timezone('UTC', now()),
  updated_at TIMESTAMP WITHOUT TIME ZONE DEFAULT timezone('UTC', now()),
  CONSTRAINT fk_patient_room
    FOREIGN KEY (room_id) REFERENCES rooms (room_id)
    ON DELETE SET NULL
    ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_patient_name ON patient (patient_name);
CREATE INDEX IF NOT EXISTS idx_admission_date ON patient (admission_date);
CREATE INDEX IF NOT EXISTS idx_patient_room_id ON patient (room_id);
CREATE INDEX IF NOT EXISTS idx_gender ON patient (gender);
CREATE INDEX IF NOT EXISTS idx_discharge_date ON patient (discharge_date);

-- [EN] Temperature calibration audit table.
-- [ZH] 溫度校正稽核資料表。
CREATE TABLE IF NOT EXISTS temperature_calibration (
  calibration_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id INTEGER NOT NULL,
  employee_id INTEGER,
  calibration_time TIMESTAMP WITHOUT TIME ZONE NOT NULL,
  manual_temperature REAL NOT NULL,
  sensor_temperature REAL NOT NULL,
  temperature_difference REAL NOT NULL,
  create_at TIMESTAMP WITHOUT TIME ZONE DEFAULT timezone('UTC', now()),
  standard_deviation NUMERIC(5, 3),
  sample_count INTEGER,
  min_temperature NUMERIC(5, 2),
  max_temperature NUMERIC(5, 2),
  calibration_details JSONB
);

CREATE INDEX IF NOT EXISTS idx_temperature_calibration_room_id ON temperature_calibration (room_id);
CREATE INDEX IF NOT EXISTS idx_temperature_calibration_employee_id ON temperature_calibration (employee_id);
CREATE INDEX IF NOT EXISTS idx_temperature_calibration_time ON temperature_calibration (calibration_time);

-- [EN] Trigger function to auto-refresh patient.updated_at in UTC on UPDATE.
-- [ZH] 觸發器函式：在 UPDATE 時自動以 UTC 更新 patient.updated_at。
CREATE OR REPLACE FUNCTION set_utc_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = timezone('UTC', now());
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_patient_set_updated_at ON patient;
CREATE TRIGGER trg_patient_set_updated_at
BEFORE UPDATE ON patient
FOR EACH ROW
EXECUTE FUNCTION set_utc_updated_at();
