CREATE TABLE IF NOT EXISTS sensor_thermal_frames (
  frame_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  sensor_id INTEGER NOT NULL,
  sensor_data_id BIGINT,
  high_temperature REAL NOT NULL,
  frame_json JSONB NOT NULL,
  "timestamp" TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT timezone('UTC', now()),
  CONSTRAINT sensor_thermal_frames_pk PRIMARY KEY (frame_id, "timestamp"),
  CONSTRAINT fk_sensor_thermal_frames_sensor
    FOREIGN KEY (sensor_id) REFERENCES sensors (sensor_id)
) PARTITION BY RANGE ("timestamp");

CREATE INDEX IF NOT EXISTS idx_sensor_thermal_frames_sensor_ts
ON sensor_thermal_frames (sensor_id, "timestamp" DESC);

CREATE INDEX IF NOT EXISTS idx_sensor_thermal_frames_sensor_data_id
ON sensor_thermal_frames (sensor_data_id);

CREATE TABLE IF NOT EXISTS sensor_thermal_frames_default
PARTITION OF sensor_thermal_frames DEFAULT;

CREATE OR REPLACE FUNCTION ensure_sensor_thermal_monthly_partitions(months_back INTEGER DEFAULT 1, months_ahead INTEGER DEFAULT 3)
RETURNS INTEGER
LANGUAGE plpgsql
AS $$
DECLARE
  base_month DATE := date_trunc('month', timezone('UTC', now()))::date;
  offset_idx INTEGER;
  from_date DATE;
  to_date DATE;
  part_name TEXT;
  created_count INTEGER := 0;
BEGIN
  IF months_back < 0 THEN
    months_back := 0;
  END IF;
  IF months_ahead < 0 THEN
    months_ahead := 0;
  END IF;

  FOR offset_idx IN (-months_back)..months_ahead LOOP
    from_date := (base_month + (offset_idx || ' month')::interval)::date;
    to_date := (from_date + interval '1 month')::date;
    part_name := format('sensor_thermal_frames_p%s', to_char(from_date, 'YYYYMM'));

    IF to_regclass('public.' || part_name) IS NULL THEN
      EXECUTE format(
        'CREATE TABLE %I PARTITION OF sensor_thermal_frames FOR VALUES FROM (%L) TO (%L)',
        part_name, from_date, to_date
      );
      created_count := created_count + 1;
    END IF;
  END LOOP;

  RETURN created_count;
END;
$$;

SELECT ensure_sensor_thermal_monthly_partitions(1, 3);

ALTER TABLE sensor_datas
DROP COLUMN IF EXISTS temperature_json;
